services:
  webapp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      ollama-setup:
        condition: service_completed_successfully
    networks:
      - app-network
    environment:
      - OLLAMA_HOST=ollama
      - PORT=80

  ollama:
    build:
      context: .
      dockerfile: Dockerfile.ollama
    volumes:
      - ollama-data:/root/.ollama
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s

  ollama-setup:
    image: alpine:latest
    depends_on:
      ollama:
        condition: service_healthy
    networks:
      - app-network
    volumes:
      - ./pull-model.sh:/pull-model.sh
    command: sh -c "apk --no-cache add curl && chmod +x /pull-model.sh && /pull-model.sh"
    environment:
      - OLLAMA_HOST=ollama

networks:
  app-network:
    driver: bridge

volumes:
  ollama-data: